name: Build and Release Flatpak

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build & Release Flatpak
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak

      - name: Build Flatpak Bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v1
        with:
          bundle: com.nestor_churin.MineImator.flatpak
          manifest-path: com.nestor_churin.MineImator.yml
          run-tests: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: com.nestor_churin.MineImator.flatpak
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
